### ISSUE TITLE
Errors on Startup

### ISSUE THREAD

**Issue by crookedneighbor** [AntJanus/hRPG-electron#2]
The Readme does not include any description of how to run it.

I cloned down the repo, ran `npm install` and `npm start` and I'm given a blank page with some console errors:

![screen shot 2016-06-04 at 8 23 27 am](https://cloud.githubusercontent.com/assets/2916945/15799786/9f262c9c-2a2d-11e6-95ec-d5c0c6af3a8a.png)

**Comment by AntJanus** [comment]
I'll add installation and run instructions.
